### ISSUE TITLE
BUG: install fails, gallium (x64, ubuntu) 

### ISSUE THREAD

**Issue by sdetweil** [Bee-Mar/mmpm#109]
**Describe the Bug**

python3 -m pip install mmpm
Collecting mmpm
  Could not find a version that satisfies the requirement mmpm (from versions: )
No matching distribution found for mmpm
Is this an issue with the CLI or GUI?

can't install, mmpm not found

tried with and without python virtual env

uname -a 
Linux galliumos 4.16.18-galliumos #1 SMP PREEMPT Sun Jun 23 04:14:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
python3 --version
Python 3.6.9

**To Reproduce**
follow instruction steps. 

doesn't say to clone repo, so install must be loading it from internet somewhere..

**Comment by Bee-Mar** [comment]
Python 3.6.9 isn't supported, only Python >= 3.7. Give that a shot a let me know how it goes.

**Comment by sdetweil** [comment]
I did this, using the wiki instructions 
```
(venv) sam@galliumos:~$ sudo apt install python3.8
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3.8 is already the newest version (3.8.13-1+bionic2).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
(venv) sam@galliumos:~$ python3 --version
Python 3.6.9
(venv) sam@galliumos:~$ 
```

**Comment by sdetweil** [comment]
and
```
sudo apt install python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3 is already the newest version (3.6.7-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 34 not upgraded.
```

**Comment by sdetweil** [comment]
trying to help user on mm discord

**Comment by Bee-Mar** [comment]
Based on the output you posted, it shows the system Python3 version is 3.8 but the version in the virtual env is 3.6.9. The virtual env would need to be recreated using Python 3.8. I'm not sure how your system or the other users system is setup, but possibly running "python3.8 -m venv venv" might be similar to what you'd need to create a virtual env with the right Python version. The MMPM executable isn't found because pip fails to install it using the Python version found in that virtual env. Hope that helps some.

**Comment by sdetweil** [comment]
```
python3.8 -m venv venv
Error: Command '['/home/sam/venv/bin/python3.8', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.
```
sorry, know nothing about python
