### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by Jan-2005** [Bee-Mar/mmpm#50]
Rapsberry Pi 3  freshly installed.

`
  The script flask is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warn                                  ing, use --no-warn-script-location.
  The script wssh is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warn                                  ing, use --no-warn-script-location.
  The script gunicorn is installed in '/home/pi/.local/bin' which is not on PATH                                  .
  Consider adding this directory to PATH or, if you prefer to suppress this warn                                  ing, use --no-warn-script-location.
  The script mmpm is installed in '/home/pi/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warn                                  ing, use --no-warn-script-location.
Successfully installed Flask-Cors-3.0.9 Jinja2-2.11.2 Werkzeug-1.0.1 argcomplete                                  -1.12.1 argparse-1.4.0 bcrypt-3.2.0 bs4-0.0.1 cffi-1.14.3 colorama-0.4.3 dnspyth                                  on-2.0.0 eventlet-0.25.1 flask-1.1.1 flask-socketio-4.3.1 greenlet-0.4.17 gunico                                  rn-20.0.4 importlib-metadata-2.0.0 mmpm-2.5 monotonic-1.5 paramiko-2.7.2 pycpars                                  er-2.20 pynacl-1.4.0 python-engineio-3.13.2 python-socketio-4.6.0 requests-2.23.                                  0 tornado-6.0.4 websocket-client-0.57.0 webssh-1.5.3 zipp-3.2.0
pi@raspberrypi:~ $ mmpm --guided-setup
-bash: mmpm: command not found `

**Comment by Bee-Mar** [comment]
you need to add `/home/pi/.local/bin` to your `PATH`. The first line in the error message states exactly what is wrong, and this is not a MMPM bug. Execute the commands below and it will be resolved

```sh
echo "export PATH=$PATH:/home/pi/.local/bin" >> /home/pi/.bashrc
source /home/pi/.bashrc
```

**Comment by JoshuaShelswell** [comment]
why is this not in the instructions

**Comment by Bee-Mar** [comment]
@JoshuaShelswell I can add this, however it was left out because whenever you install a package with `pip` that includes a command line entry point executable like `mmpm` a yellow warning message is displayed on screen that says the executable is not in your path. This example is on a Windows machine, but it is similar on Linux/MacOS

https://github.com/pypa/pip/issues/5316

**Comment by JoshuaShelswell** [comment]
i see but this should probably be in the instructions regardless since you have to put it in to use mmpm --guided-setup after install on a raspberrypi and not everyone new to linux knows how to make an echo command to add something to the path to use your program should add a disclaimer noting like "if you run into this message and cant use the guided setup" etc, i wouldnt have gotten this running if i didnt find this bug report
