### ISSUE TITLE
BUG: Inconsistent naming convention on 3rd party pages causes uninstallable/harder to install modules

### ISSUE THREAD

**Issue by Luc-Veldhuis** [Bee-Mar/mmpm#56]
**Describe the Bug**

Is this an issue with the CLI or GUI? Both

Is this something that should be put in the Wiki? Should be fixed by the MagicMirror wiki editors

**To Reproduce**
1. Go to https://github.com/MichMich/MagicMirror/wiki/3rd-Party-Modules
2. Click on Daily Pokemon
The repo name (has changed?) is MMM-DailyPokemon, when installing the Daily Pokemon package, it will place it in a folder named Daily Pokemon, but in the README it will say to name the module MMM-DailyPokemon.
Changing the name of the folder fixes this issue, but I noticed multiple of these occurences. (https://github.com/alexBeuth/MMM-germanwordclock as well)

**Expected behavior**
I expected the naming of the repo and the 3rd party page to be the same.

I am unsure if this should be an issue on this page or on the MagicMirror repo. I am sorry if I placed it in the wrong location.

**Comment by Bee-Mar** [comment]
This isn't a bug, and is a result of the creator of the "Daily Pokemon" package listing it with an inconsistent name on the 3rd party wiki. When you're about to install the package, you should see the URL of "Daily Pokemon" as [https://github.com/NolanKingdon/MMM-DailyPokemon](https://github.com/NolanKingdon/MMM-DailyPokemon) (as seen below). The project is actually named MMM-DailyPokemon, and git downloads the repository into a directory named the same as the project, unless you supply additional arguments. MMPM doesn't manipulate the name of the directory to match the name of what's listed on the 3rd party wiki, since the 3rd party wiki is more likely to change than the actual name of the project.

(sample output of the installation for MMM-DailyPokemon)
```sh
Install Daily Pokemon (https://github.com/NolanKingdon/MMM-DailyPokemon)? [yes/y] or [no/n]: yes
+ Installing Daily Pokemon
---- Cloning repository ✓
---- Found package.json. Running `npm install` ✓
---- Installation complete ✓
Run `mmpm open --config` to edit the configuration for newly installed modules


```
